<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="simple_vehicle">

  <!-- 기본 파라미터 -->
  <xacro:property name="wheel_radius" value="0.05"/>      <!-- 50 mm -->
  <xacro:property name="wheel_width" value="0.02"/>       <!-- 20 mm -->
  <xacro:property name="wheelbase" value="0.335"/>        <!-- 335 mm -->
  <xacro:property name="vehicle_length" value="0.567"/>   <!-- 567 mm -->
  <xacro:property name="vehicle_height" value="0.214"/>   <!-- 214 mm -->
  <xacro:property name="vehicle_width" value="0.25"/>     <!-- 250 mm -->

  <!-- 재질 정의 -->
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <!-- 차체 링크 -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${wheel_radius + vehicle_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${vehicle_length} ${vehicle_width} ${vehicle_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${wheel_radius + vehicle_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${vehicle_length} ${vehicle_width} ${vehicle_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10.0"/>
      <origin xyz="0 0 ${wheel_radius + vehicle_height/2.0}" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- 휠 위치 계산 -->
  <xacro:property name="wheel_x_offset" value="${wheelbase/2.0}"/>
  <xacro:property name="wheel_y_offset" value="${vehicle_width/2.0 - wheel_width/2.0}"/>

  <!-- 바퀴 매크로 정의 -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      </inertial>
    </link>
    <joint name="${name}_joint" type="continuous">
      <origin xyz="${x} ${y} ${wheel_radius}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${name}"/>
      <axis xyz="0 1 0"/>
    </joint>
    <!-- Differential drive transmission -->
    <transmission name="${name}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_joint">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_motor">
        <hardwareInterface>PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <!-- 4개 바퀴 생성 -->
  <xacro:wheel name="front_left_wheel"  x="${wheel_x_offset}"  y="${wheel_y_offset}"/>
  <xacro:wheel name="front_right_wheel" x="${wheel_x_offset}"  y="-${wheel_y_offset}"/>
  <xacro:wheel name="rear_left_wheel"   x="-${wheel_x_offset}" y="${wheel_y_offset}"/>
  <xacro:wheel name="rear_right_wheel"  x="-${wheel_x_offset}" y="-${wheel_y_offset}"/>

  <!-- Gazebo ros control plugin for differential drive -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
  </gazebo>

  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros2ControlPlugin>diff_drive_controller/DiffDriveController</ros2ControlPlugin>
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      <wheel_separation>${vehicle_width - 2.0*wheel_radius}</wheel_separation>
      <wheel_diameter>${2.0*wheel_radius}</wheel_diameter>
      <topic_name>cmd_vel</topic_name>
      <update_rate>100</update_rate>
    </plugin>
  </gazebo>

</robot>
